# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07b26d7a21f3b686e6f6e631659988f7ff6b4ac01513adb83003d34821bb8ff742f4a37fa47c85653016d7196b2c2d6a915bed328c810ff7dd579a842f66a86d

test:
  secret_key_base: d2ce0fd0bcbb9fe02732688dd1192c434912f5cbcce652253ab477ba5171a72d93b47a0c2f4dd9660a6d5b9da18c9cf02972f28f7ed3b573a7c4281bca33f972

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
